apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mongodb-data
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hostpath
  hostPath:
    path: /home/sebastian/docker_2025/Corte_3/database
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mongodb-backup
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hostpath
  hostPath:
    path: /home/sebastian/docker_2025/Corte_3/backup

